### ISSUE TITLE
doesn't work on iPad with iOS 8.1

### ISSUE THREAD

**Issue by haemi** [carezone/CZPhotoPickerController#16]
everything works as expected on iPhone, but whenever I try the same code on iPad, I only get the overview with "Use Last Photo Taken", "Take Photo" and "Choose from Library". From these three options, only the first one works. Whenever I press "Take Photo" or "Choose from Library", the popover disappears and nothings happens.

I'm using CZPhotoPickerController the same way as described here:

```
    self.photoPicker = [[CZPhotoPickerController alloc] initWithPresentingViewController:self withCompletionBlock:^(UIImagePickerController *imagePickerController, NSDictionary *imageInfoDict) {
...

    [self.photoPicker showFromBarButtonItem:self.navigationItem.rightBarButtonItem];
```

**Comment by peymano** [comment]
I just tried the example app on my iPad running 8.1.2 and it worked fine. Are you still seeing this issue @haemi ?

**Comment by Xean** [comment]
I do. Same as ahem and the code from arno608rw doesn't work, too. I am testing with my iPhone 5s, iOS 8.1.2.

**Comment by peymano** [comment]
Please try the latest release `1.2.4`.

**Comment by fatuhoku** [comment]
Has this been fixed for iOS 8.3

**Comment by peymano** [comment]
Yes. Please let me know if you run into any issues.

**Comment by fatuhoku** [comment]
@peymano Great cheers!  Seems to work fine for me  =]
