### ISSUE TITLE
1.2.3 not on cocoapods repo

### ISSUE THREAD

**Issue by joshwalker** [carezone/CZPhotoPickerController#17]
I see that the podfile was bumped to 1.2.3 to fix iOS 8 issues.  This fixed worked for me, but I have to point my Podfile directly to your git repo because they aren't reflecting the current version.

**Comment by peymano** [comment]
Sorry about that. I just pushed up `1.2.3` to Cocoapods: https://github.com/CocoaPods/Specs/commit/d53c252787f808409ab5bbcfc82ce3fb7ed7c824
