### ISSUE TITLE
Custom items

### ISSUE THREAD

**Issue by fatuhoku** [carezone/CZPhotoPickerController#20]
Hi, thanks for the component.

I actually want to extend the action sheet that gets presented by `CZPhotoPickerController`, to include a 'Delete photo' option. Perhaps a delegate for additional action sheet options would be nice.

**Comment by yas375** [comment]
Where do you want to delete the photo from? From user photo library?

**Comment by fatuhoku** [comment]
@yas375 No, imagine an UIImageView, that when a user touches it, activates CZPhotoPicker.

The popover offers a number of things you might want to do with that image.

A custom action that'll be useful is to Delete the Photo.

So I guess this is a custom action that can do anything, really.
